### ISSUE TITLE
Router created for mesh service

### ISSUE THREAD

**Issue by dtomcej** [containous/maesh#156]
Routers are now created for mesh services:
 ```yaml
   "routers": {
        "32b7c4a461ec6d539cac7d3d8bb1da7b764b43f39712d5243924449d9563b145@rest": {
            "entryPoints": [
                "ingress-5000"
            ],
            "service": "32b7c4a461ec6d539cac7d3d8bb1da7b764b43f39712d5243924449d9563b145",
            "rule": "Host(`default-whoami-http-whoami.default.i3o`) || Host(`10.43.109.213`)",
            "status": "enabled"
        },
        "502e81d8f47b115e6675661ae94e616eca917b2cfde8c0e19fcaa44fcbca0a11@rest": {
            "entryPoints": [
                "ingress-5000"
            ],
            "service": "502e81d8f47b115e6675661ae94e616eca917b2cfde8c0e19fcaa44fcbca0a11",
            "rule": "Host(`default-whoami-whoami.default.i3o`) || Host(`10.43.213.60`)",
            "status": "enabled"
        },
        "9e80f3ef1bd463c2d3baf8bc1cfcce64cef43518a6ba6977229b89a79fdd0747@rest": {
            "entryPoints": [
                "ingress-5000"
            ],
            "service": "9e80f3ef1bd463c2d3baf8bc1cfcce64cef43518a6ba6977229b89a79fdd0747",
            "rule": "Host(`whoami-http.whoami.i3o`) || Host(`10.43.63.74`)",
            "status": "enabled"
        },
        "9fb41f1b6a35ef9f532e442bb245564db52ac855a1d53eee658bf492a92ff786@rest": {
            "entryPoints": [
                "ingress-5000"
            ],
            "service": "9fb41f1b6a35ef9f532e442bb245564db52ac855a1d53eee658bf492a92ff786",
            "rule": "Host(`whoami.whoami.i3o`) || Host(`10.43.244.119`)",
            "status": "enabled"
        },
```

Routers should only be created for user services.
