### ISSUE TITLE
Mesh-pods not ready

### ISSUE THREAD

**Issue by frelon** [containous/maesh#286]
I have deployed maesh to a 1.15.3 cluster using flannel as CNI.

The mesh pods seem to not pass the readiness-check because <pod-ip>:1081/ping returns 404.

```
> kubectl get pods -n maesh
NAME                               READY   STATUS    RESTARTS   AGE
jaeger-89949667d-zv56k             1/1     Running   0          2m29s
maesh-controller-f6d8567f7-8vwf8   1/1     Running   0          3m9s
maesh-mesh-9gdgk                   0/1     Running   0          2m38s
maesh-mesh-ftrbc                   0/1     Running   0          2m49s
maesh-mesh-mvdrn                   0/1     Running   0          2m40s
```

Describe:
```
> kubectl describe pod maesh-mesh-mvdrn
... cropped ...
Events:
  Type     Reason     Age                     From                  Message
  ----     ------     ----                    ----                  -------
  Normal   Scheduled  3m37s                   default-scheduler     Successfully assigned maesh/maesh-mesh-mvdrn to k8s-app-n03
  Normal   Pulled     3m36s                   kubelet, k8s-app-n03  Container image "groundnuty/k8s-wait-for:v1.2" already present on machine
  Normal   Created    3m36s                   kubelet, k8s-app-n03  Created container wait-for-jaeger-init
  Normal   Started    3m36s                   kubelet, k8s-app-n03  Started container wait-for-jaeger-init
  Normal   Pulled     3m34s                   kubelet, k8s-app-n03  Container image "traefik:v2.0" already present on machine
  Normal   Created    3m34s                   kubelet, k8s-app-n03  Created container maesh-mesh
  Normal   Started    3m34s                   kubelet, k8s-app-n03  Started container maesh-mesh
  Warning  Unhealthy  3m13s (x19 over 3m31s)  kubelet, k8s-app-n03  Readiness probe failed: HTTP probe failed with statuscode: 404
```

Logs of pod:
```
> kubectl logs maesh-mesh-mvdrn                                                                                                                                                13:41:15
time="2019-10-16T11:36:29Z" level=info msg="Configuration loaded from flags."
time="2019-10-16T11:36:29Z" level=info msg="Traefik version 2.0.2 built on 2019-10-09T19:26:05Z"
time="2019-10-16T11:36:29Z" level=info msg="\nStats collection is disabled.\nHelp us improve Traefik by turning this feature on :)\nMore details on: https://docs.traefik.io/v2.0/contributing/data-collection/\n"
time="2019-10-16T11:36:29Z" level=warning msg="Could not initialize jaeger tracer: lookup jaeger-agent.maesh.svc.cluster.local on 10.233.0.3:53: no such host"
time="2019-10-16T11:36:29Z" level=warning msg="Unable to create tracer: lookup jaeger-agent.maesh.svc.cluster.local on 10.233.0.3:53: no such host"
time="2019-10-16T11:36:29Z" level=info msg="Starting provider aggregator.ProviderAggregator {}"
time="2019-10-16T11:36:29Z" level=info msg="Starting provider *rest.Provider {\"insecure\":true}"
```
Values for helm-deploy:
```yaml
## Default values for maesh
controller:
  image:
    name: containous/maesh
    pullPolicy: IfNotPresent
    tag: v0.5.0
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging:
    debug: true
  ignoreNamespaces:
  # Added so we can launch on nodes with restrictions
  nodeSelector: 
    kubernetes.io/os: "linux"
  tolerations: []
  affinity: {}

kubedns: false

mesh:
  image:
    name: traefik:v2.0
    pullPolicy: IfNotPresent
  resources:
    limit:
      mem: "100Mi"
      cpu: "200m"
    request:
      mem: "50Mi"
      cpu: "100m"
  logging: INFO
  defaultMode: http
  # Added so we can launch on nodes with restrictions
  tolerations: []

#
# addon jaeger tracing configuration
#
tracing:
  deploy: true
  jaeger:
    image: 
      name: groundnuty/k8s-wait-for:v1.2
    enabled: true
    localagenthostport: ""
    samplingserverurl: ""

#
# addon metrics configuration
#
metrics:
  deploy: false
  prometheus:
    enabled: false

smi: false

limits:
  http: 10
  tcp: 25
```
I have installed maesh using helm from the git-repo:
```
helm install maesh --namespace=maesh . -f override-values.yaml
helm list                                                                                                                                                                   13:47:32
NAME    NAMESPACE       REVISION        UPDATED                                         STATUS          CHART           APP VERSION
maesh   maesh           1               2019-10-16 13:35:56.278050594 +0200 CEST        deployed        maesh-0.0.7     v0.6.0
```

Any suggestions?
