### ISSUE TITLE
Panic when getting applicable traffic targets on nil endpoint list

### ISSUE THREAD

**Issue by Ullaakut** [containous/maesh#358]
### Bug

When given an invalid configuration, which has no endpoints, in `func (p *Provider) BuildConfig() (*dynamic.Configuration, error)`, at line 92, we do the following:

```go
applicableTrafficTargets := p.getApplicableTrafficTargets(base.GetEndpointsFromList(service.Name, service.Namespace, endpoints), trafficTargetsInNamespace)
```

Which runs `base.GetEndpointsFromList` and passes those endpoints to `p.getApplicableTrafficTargets`.

`GetEndpointsFromList` can return a nil pointer:

```go
// GetEndpointsFromList returns an endpoint from a list.
func GetEndpointsFromList(name, namespace string, endpointList []*corev1.Endpoints) *corev1.Endpoints {
	for _, endpoints := range endpointList {
		if endpoints.Name == name && endpoints.Namespace == namespace {
			return endpoints
		}
	}

	return nil
}
```

Which is then misused in `getApplicableTrafficTargets`:

```go
func (p *Provider) getApplicableTrafficTargets(endpoints *corev1.Endpoints, trafficTargets []*accessv1alpha1.TrafficTarget) []*accessv1alpha1.TrafficTarget {
	var result []*accessv1alpha1.TrafficTarget

	if len(endpoints.Subsets) == 0 { // Panic here.
		log.Debugf("No applicable TrafficTargets for service %s/%s: No endpoint subsets", endpoints.Namespace, endpoints.Name)
	}
```

And triggers the following panic error:

```go
...
github.com/containous/maesh/internal/providers/smi.(*Provider).getApplicableTrafficTargets(0xc0000f7ee8, 0x0, 0xc000286028, 0x1, 0x1, 0x1, 0x1, 0x0)
	/Users/ullaakut/Work/go/src/github.com/containous/maesh/internal/providers/smi/provider.go:201 +0x3a
github.com/containous/maesh/internal/providers/smi.(*Provider).BuildConfig(0xc0000f7ee8, 0x1, 0x1, 0xc0002dc000)
...
```

### How to reproduce this bug

Call `BuildConfig` with this configuration:

<details>
<summary>config.yaml</summary>

```yaml
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: example-traffic-target
destination:
  kind: ServiceAccount
  name: api-service
  namespace: foo
sources:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
specs:
  - kind: TCPRoute
    name: api-service-routes
---
kind: TCPRoute
apiVersion: specs.smi-spec.io/v1alpha1
metadata:
  name: api-service-routes

---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: foo
  annotations:
    maesh.containo.us/traffic-type: tcp
spec:
  clusterIP: 10.1.0.1
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: demo-service
subsets:
- addresses:
  - ip: 10.1.1.50
    targetRef:
      name: example
      namespace: default
  ports:
  - port: 50

---
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  serviceAccountName: api-service
  containers:
    - name: example
      image: busybox
status:
  podIP: "10.4.3.2"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  clusterIP: 10.1.0.1
  ports:
  - protocol: TCP
    port: 80
    name: web
```

</details>

**Comment by Ullaakut** [comment]
Another similar panic can be found in the same file, where we try to access `address.TargetRef.Namespace` and `address.TargetRef.Name` while `address.TargetRef` can be nil:

```go
			for _, address := range subset.Addresses {
				pod, exists, err := p.client.GetPod(address.TargetRef.Namespace, address.TargetRef.Name)
				if err != nil {
					log.Errorf("Could not get pod %s/%s: %v", address.TargetRef.Namespace, address.TargetRef.Name, err)
					continue
				}
```

Which trigger the following panic:

```go
...
github.com/containous/maesh/internal/providers/smi.(*Provider).getApplicableTrafficTargets(0xc0003a1ee8, 0xc000296140, 0xc0002dc870, 0x1, 0x1, 0x1, 0x1, 0xc000296140)
	/Users/ullaakut/Work/go/src/github.com/containous/maesh/internal/providers/smi/provider.go:236 +0x4d8
github.com/containous/maesh/internal/providers/smi.(*Provider).BuildConfig(0xc0003a1ee8, 0x1, 0x1, 0xc0002b4000)
	/Users/ullaakut/Work/go/src/github.com/containous/maesh/internal/providers/smi/provider.go:92 +0xacb
...
```

Here is a configuration to use in order to reproduce it:

<details>
<summary>config.yaml</summary>

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: foo
---
apiVersion: v1
kind: Service
metadata:
  name: test
  namespace: foo
  annotations:
    maesh.containo.us/traffic-type: tcp
spec:
  clusterIP: 10.1.0.1
  selector:
    app: test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: example-traffic-target
destination:
  kind: ServiceAccount
  name: api-service
  namespace: foo
sources:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
specs:
  - kind: TCPRoute
    name: api-service-routes
---
kind: TCPRoute
apiVersion: specs.smi-spec.io/v1alpha1
metadata:
  name: api-service-routes
---
apiVersion: v1
kind: Endpoints
metadata:
  name: test
  namespace: foo
subsets:
  - addresses:
      - ip: 10.0.0.1
    ports:
      - port: 80
  - addresses:
      - ip: 10.0.0.2
    ports:
      - port: 80
```

</details>

**Comment by Ullaakut** [comment]
Yet another one is in `getMeshPort`, at line 554, where we try to access `p.tcpStateTable.Table` while `p.tcpStateTable` can be `nil`:

```go
func (p *Provider) getMeshPort(serviceName, serviceNamespace string, servicePort int32) int {
	for port, v := range p.tcpStateTable.Table {
		if v.Name == serviceName && v.Namespace == serviceNamespace && v.Port == servicePort {
			return port
		}
	}
```

Which results in the following panic:

```go
...
github.com/containous/maesh/internal/providers/smi.(*Provider).getMeshPort(0xc00049bee8, 0xc0005065c0, 0xc, 0x1d93c1b, 0x7, 0x50, 0x1)
	/Users/ullaakut/Work/go/src/github.com/containous/maesh/internal/providers/smi/provider.go:555 +0x3b
github.com/containous/maesh/internal/providers/smi.(*Provider).BuildConfig(0xc00049bee8, 0x1, 0x1, 0xc00026a000)
	/Users/ullaakut/Work/go/src/github.com/containous/maesh/internal/providers/smi/provider.go:136 +0x18d4
...
```

Here is the config to reproduce it:

<details>
<summary>config.yaml</summary>

```yaml
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: example-traffic-target
destination:
  kind: ServiceAccount
  name: api-service
  namespace: default
sources:
  - kind: ServiceAccount
    name: prometheus
    namespace: default
specs:
  - kind: TCPRoute
    name: api-service-routes

---
kind: TCPRoute
apiVersion: specs.smi-spec.io/v1alpha1
metadata:
  name: api-service-routes

---
apiVersion: v1
kind: Endpoints
metadata:
  name: demo-service
subsets:
  - addresses:
      - ip: 10.1.1.50
        targetRef:
          name: example
          namespace: default
    ports:
      - port: 50

---
apiVersion: v1
kind: Pod
metadata:
  name: example
spec:
  serviceAccountName: api-service
  containers:
    - name: example
      image: busybox
status:
  podIP: "10.4.3.2"

---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
  annotations:
    maesh.containo.us/traffic-type: tcp
spec:
  clusterIP: 10.1.0.1
  ports:
    - protocol: TCP
      port: 80
      name: web
```

</details>
