### ISSUE TITLE
Please provide a working SMI example

### ISSUE THREAD

**Issue by rkr-kununu** [containous/maesh#412]
#### Proposal

I'm really excited about the SMI support that Maesh has.  However, I'm unable to get a very simple example to work.  A fully functional example would be very helpful.

#### Background

I've installed Maesh v1.1-rc0 with helm (v3.0.2) by running:
`helm install maesh --namespace=maesh maesh/maesh --set smi.enable=true`

Then I followed the instructions outlined here: https://docs.mae.sh/v1.1/examples/

Afterward, I tried to create the proper SMI resources:
```
---
apiVersion: specs.smi-spec.io/v1alpha1
kind: HTTPRouteGroup
metadata:
  name: http-everything
  namespace: whoami
matches:
- name: everything
  pathRegex: ".*"
  methods: ["*"]
---
kind: TrafficTarget
apiVersion: access.smi-spec.io/v1alpha1
metadata:
  name: whatever
  namespace: whoami
destination:
  kind: ServiceAccount
  name: whoami-server
  namespace: whoami
  port: 80
specs:
- kind: HTTPRouteGroup
  name: http-everything
  matches:
  - everything
sources:
- kind: ServiceAccount
  name: whoami-client
  namespace: whoami
```

Unfortunately, when I run:
`kubectl -n whoami exec whoami-client -- curl -s whoami.whoami.maesh`

I get a HTTP-404.

#### Workarounds

None I know of.
