### ISSUE TITLE
Service with a named targetPort cannot be queried through Maesh proxy

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#517]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?

Deploy a Kubernetes Service with a named `targetPort` and queried the exposed endpoint through Maesh with `curl`. 

### What did you expect to see?

`HTTP 200 OK`.

### What did you see instead?

`HTTP 503 Service Unavailable`.

### Output of controller log: (_What version of Maesh are you using?_)

Not available.

### What is your environment & configuration (arguments, provider, platform, ...)?

Not available.

### If applicable, please paste the yaml objects required to reproduce your issue

```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: maesh-test
  labels:
    app: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: containous/whoami:v1.4.0
          ports:
            - name: http
              containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: server
  namespace: maesh-test
spec:
  type: ClusterIP
  selector:
    app: server
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: http
```

### Curl Output

```
/ # curl server.maesh-test.svc.cluster.local
Hostname: server-5594994d7d-htnpg
IP: 127.0.0.1
IP: ::1
IP: 10.244.1.115
IP: fe80::68b6:f3ff:fe24:1250
RemoteAddr: 10.244.1.111:39258
GET / HTTP/1.1
Host: server.maesh-test.svc.cluster.local
User-Agent: curl/7.64.0
Accept: */*
/ # curl server.maesh-test.maesh -v
*   Trying 10.96.139.130...
* TCP_NODELAY set
* Expire in 200 ms for 4 (transfer 0x56310e38d620)
* Connected to server.maesh-test.maesh (10.96.139.130) port 80 (#0)
> GET / HTTP/1.1
> Host: server.maesh-test.maesh
> User-Agent: curl/7.64.0
> Accept: */*
>
< HTTP/1.1 503 Service Unavailable
< Date: Tue, 21 Apr 2020 17:35:31 GMT
< Content-Length: 19
< Content-Type: text/plain; charset=utf-8
<
* Connection #0 to host server.maesh-test.maesh left intact
```
