### ISSUE TITLE
TrafficTarget deployed in the default namespace does not work

### ISSUE THREAD

**Issue by kevinpollet** [containous/maesh#546]
### What did you do?

Deployed a `TrafficTarget` in the `default` namespace to allow `HTTP` traffic from a client pod to a `whoami` service. The same deployment works if the `TrafficTarget` is not deployed in the `default` namespace.

### What did you expect to see?

`HTTP 200 OK`

### What did you see instead?

`HTTP 403 Forbidden`

### What is your environment & configuration?

ACL mode enabled.

### If applicable, please paste the yaml objects required to reproduce your issue

- **acl.yml**

```yaml
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: client-account

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: whoami-account

---
apiVersion: specs.smi-spec.io/v1alpha1
kind: HTTPRouteGroup
metadata:
  name: http-routes
matches:
  - name: everything
    pathRegex: ".*"
    methods: ["*"]

---
apiVersion: access.smi-spec.io/v1alpha1
kind: TrafficTarget
metadata:
  name: traffic-target
destination:
  kind: ServiceAccount
  name: whoami-account
  port: "80"
specs:
  - kind: HTTPRouteGroup
    name: http-routes
sources:
  - kind: ServiceAccount
    name: client-account
```

- **client.yml**

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      serviceAccountName: client-account
      containers:
        - name: client
          image: giantswarm/tiny-tools:3.9
          command:
            - "sleep"
            - "3600"
```

- **whoami.yml**

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: whoami
spec:
  selector:
    app: whoami
  ports:
    - port: 80

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami
spec:
  selector:
    matchLabels:
      app: whoami
  template:
    metadata:
      labels:
        app: whoami
    spec:
      serviceAccountName: whoami-account
      containers:
        - name:  whoami
          image: containous/whoami
```
