### ISSUE TITLE
support for jaeger daemonset in helm chart

### ISSUE THREAD

**Issue by kernel164** [containous/maesh#617]
Please support jaeger daemonset in helm chart. link => https://www.jaegertracing.io/docs/1.18/operator/#installing-the-agent-as-daemonset

e.g
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: acme/myapp:myversion
        env:
        - name: JAEGER_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```
