### ISSUE TITLE
whoami with traffic split doesn't work

### ISSUE THREAD

**Issue by kernel164** [containous/maesh#619]
### What did you do?

EKS
k8s 1.16
Maesh 1.2.0

Tried setting whoami as per => https://docs.mae.sh/examples/
extended it to support v1, v2 with traffic split

With 
```
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: whoami-trafficsplit
  namespace: maesh-demo
spec:
  service: whoami
  backends:
    - service: whoami-v1
      weight: 1
    - service: whoami-v2
      weight: 1
```

I get 

```
maesh-controller 2020-05-31T05:08:46.332119499Z time="2020-05-31T05:08:46Z" level=error msg="Error building topology for TrafficSplit \"whoami-trafficsplit@maesh-demo\": unable to find root Service \"whoami@maesh-demo\""
```

with 

```
apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: whoami-trafficsplit
  namespace: maesh-demo
spec:
  service: whoami-v1
  backends:
    - service: whoami-v1
      weight: 1
    - service: whoami-v2
      weight: 1
```

I get 
```
maesh-controller-5cd7d56465-2cfv2 maesh-controller 2020-05-31T05:22:11.145940168Z time="2020-05-31T05:22:11Z" level=error msg="Error building topology for TrafficSplit \"whoami-trafficsplit@maesh-demo\": unable to get incoming pods: circular reference detected on TrafficSplit \"whoami-trafficsplit@maesh-demo\" in Service \"whoami-v1@maesh-demo\""
```

Am I doing it right?
