### ISSUE TITLE
support for env, envFrom, extraArgs in helm chart.

### ISSUE THREAD

**Issue by kernel164** [containous/maesh#621]
Please support env, envFrom and extraArgs in helm chart.

Something like this.

```
{{- with .Values.additionalArguments }}
          {{- range . }}
          - {{ . | quote }}
          {{- end }}
          {{- end }}
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 10 }}
        {{- end }}
```

**Comment by kernel164** [comment]
I think support for this issue should solve #617

I can solve #617 using following values.

```
env:
    - name: JAEGER_AGENT_HOST
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
  additionalArguments:
    - "--tracing.jaeger=true"
    - "--tracing.jaeger.samplingServerURL=http://$(JAEGER_AGENT_HOST):5778/sampling"
    - "--tracing.jaeger.localAgentHostPort=$(JAEGER_AGENT_HOST):6831"
```

traefik helm chart supports this already.
